### ISSUE TITLE
OPTiMaDe logo

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/materials-consortia.github.io#1]
Dear colleagues,

it's not a secret that nowadays any successful and recognized public activity needs a clear visual identification (branding). Being scientifically important and promising cross-disciplinary initiative, OPTiMaDe obviously needs such branding.

Herewith I'd like to contribute hiring a designer and developing a professional logo, but first I need **YOUR** input.

Dear colleagues, please, share your ideas.

**Comment by blokhin** [comment]
![optimade](https://user-images.githubusercontent.com/177388/56459862-192cf180-639a-11e9-8638-e62b873d71d4.jpg)

The current logo is nice, but has some deficiencies in visual communication:
- no transparent background
- horizontally very stretched
- hard to perceive due to numerous details
_etc._

**Comment by blokhin** [comment]
I attach a slide from some of my recent talks, to tease your imagination.

![2019-04-20_18-42-04](https://user-images.githubusercontent.com/177388/56460000-2d71ee00-639c-11e9-9b88-e704a34ef869.png)

**Comment by gmrigna** [comment]
Dear Evgeny,
Thanks for the initiative. It is really appreciated!
What we have is not at all a logo. It is just a piece of the poster that was created by the Lorentz center for our [first workshop](http://www.lorentzcenter.nl/lc/web/2016/826/info.php3?wsid=826&venue=Snellius) on which "OPTiMaDe" has been written. So, it does indeed have all the deficiencies that you indicate (and probably more).
It is thus really kind of you to be willing to contribute hiring a designer and developing a professional logo.
Here are my first thoughts. Possibly, the logo should carry the idea that there is various databases (this probably is what lead to the oval boxes in the Lorentz center poster) connected through one API. Ideally, it should also indicate that it is about materials.

**Comment by blokhin** [comment]
See https://github.com/Materials-Consortia/OPTiMaDe/issues/67 for the further discussion.
