### ISSUE TITLE
Fonts perhaps not working as intended?

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/materials-consortia.github.io#22]
It looks like the intention was to use the "Overpass" font, at least for the menu items, but this font is not being loaded anywhere so will only work if the user has it installed locally. We also mix fonts elsewhere, with the body and header text defaulting to `font-family:'Lucida Grande', 'Calibri', Helvetica, Arial, sans-serif;` (which itself I think is set by github pages as a fallback).

Would anyone have any objections to a PR that fixes this, and sets all fonts on the site Overpass, with a fallback of "sans-serif"?

**Comment by ml-evs** [comment]
It would look like this:

![image](https://user-images.githubusercontent.com/7916000/85546731-1b7d8200-b615-11ea-8a37-8464ac8ef295.png)

**Comment by gmrigna** [comment]
Thanks for spotting this and proposing a PR...

**Comment by rartino** [comment]
Hmm... do our present buttons render like in your screenshot for you? For me they render more vertically centered. See the following screenshot that compares the two. Mine is the upper, your screenshot is the lower:

![Screenshot from 2020-06-24 23-26-04](https://user-images.githubusercontent.com/2890905/85629786-c6705900-b672-11ea-879d-359cc57a68bf.png)

**Comment by ml-evs** [comment]
Here's what it looks like for me without any changes on Linux (without many fonts locally installed):

![image](https://user-images.githubusercontent.com/7916000/85630708-0ed84880-b66c-11ea-9a93-6bbe87ec149a.png)

**Comment by rartino** [comment]
So, do I understand correctly that the only difference between your first and second screenshot is the use of the Overpass font? 

In that case I vote against the Overpass font without also adjusting the text to be properly centered on the buttons. (But looking at it now, I kind of also like better the bolder look of the non-overpass version, but I feel less strongly about that.)

**Comment by ml-evs** [comment]
I would be happy with consistent Arial/Helvetica/sans-serif throughout.
