### ISSUE TITLE
Temporarily remove Swagger links for Materials Project and Materials Cloud

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/materials-consortia.github.io#33]
> In the "Swagger" section, the links to the Materials Project and the Materials Cloud lead to "Failed to load API definition."
> The problem may be related to cross-origin (CORS) issue ("Access-Control-Allow-Origin").

For Materials Cloud, I think this is related to the issue that one cannot reach the generated OpenAPI JSON for the implementations. See also Materials-Consortia/optimade-python-tools#520, which I think is the cause of the endpoint not being reachable.

Also, this was the reason for not yet merging it. But I guess it's fine. We should probably remove those links until it's fixed though!

_Originally posted by @CasperWA in https://github.com/Materials-Consortia/materials-consortia.github.io/issues/30#issuecomment-809193883_

**Comment by ml-evs** [comment]
Hmm, must have only tested the odbx swagger link (which works) before merging. Not sure why odbx is unaffected. I guess I am using gunicorn rather than uvicorn, which must be handling the `base_url` properly?

Apologies for merging, there was no comment about this and it shouldn't take 5 months to get a PR like that in :grin:

**Comment by CasperWA** [comment]
> Apologies for merging, there was no comment about this and it shouldn't take 5 months to get a PR like that in 😁

Indeed. I blame myself entirely. I should have removed these links right away. It simply slid off my radar a bit. But give me 2 min. and I'll have something you can review and we can merge immediately. Then I'll create a draft PR to return the links, which can be merged when the issue is fixed.
