### ISSUE TITLE
Certificate for web forwarding on root domain https://optimade.org has expired

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/materials-consortia.github.io#55]
@gmrigna 

We need a renewed cert from your IT dept / Sectigo. I'm guessing they didn't contact you about this already?

(Note: I had a monitoring on this meant to alert us a bit ahead of expiry, but I missed it because it was obfuscated by irrelevant alerts... I'm going to have to clean this setup up a bit.)

**Comment by gmrigna** [comment]
I am just back from vacation and I am discussing this with our system administrators...

**Comment by rartino** [comment]
This is now fixed; thanks to Gian-Marco and the uclovain IT department. However, I have some trouble with providers.optimade.org.
