### ISSUE TITLE
Update website for v1.0.0-rc1 release, including new logo

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/materials-consortia.github.io#7]
I'm working on some updates in my fork of this repository, hosted here:
- https://rartino.github.io/materials-consortia.github.io/

**Comment by blokhin** [comment]
![2020-02-08_16-03-30](https://user-images.githubusercontent.com/177388/74087445-97bf6080-4a8c-11ea-9d45-cf9ea0931d14.png)

Please, could you add the small vertical margin to the menu items?

**Comment by gmrigna** [comment]
Really cool!!!

**Comment by rartino** [comment]
@blokhin Does it look better for you now?

**Comment by gmrigna** [comment]
Looking at it again, there seems to be a lot of white... Could you try to have the buttons at the top colored with white text?

**Comment by CasperWA** [comment]
Looks good!
Should we update the list of database providers as well, while we're at it?

**Comment by rartino** [comment]
![Screenshot from 2020-06-13 11-30-55](https://user-images.githubusercontent.com/2890905/84565424-65d74700-ad69-11ea-84a3-9aac483e60af.png)

So, does this look better? I'm not sure :)

**Comment by blokhin** [comment]
Please, merge

**Comment by gmrigna** [comment]
Let me ask a friend who is a graphic designer...

**Comment by giovannipizzi** [comment]
Looks very good to me, and ready to merge! Of course ok if @gmrigna wants to check first

**Comment by rartino** [comment]
There is now a PR at #16.
